### ISSUE TITLE
Be able to share information to groups you are member of

### ISSUE THREAD

**Issue by despiegk** [itsyouonline/identityserver#134]
use case explanation

e.g. group X has user a,b,c,d
a robot managing support process for this group needs to have access to tel nrs & email addr of users in this group.

**Comment by robvanmieghem** [comment]
Let's not introduce an extra management screen, itsyou.online is already too much of an administration tool.
1. Rework the invitation acceptance, instead of checkboxes and the ability to accept all, have a seperate accept/decline button for each invitation
2. When clicking the accept button, the authorize screen is shown with an authorization for all communication channels (email, phone number for now).
