### ISSUE TITLE
When logging into the website I receive two SMS's doing 2 factor authentication

### ISSUE THREAD

**Issue by lzonneke** [itsyouonline/identityserver#163]
## scenario
- sign in (itsyou.online)
- add username and password
- login
- press "send autentication"

now I receive multiple SMS's

## expected result
I would expect to receive only one sms's

**Comment by lucasvanhalst** [comment]
That's because an sms is send automatically if you only have 1 SMS number configured as two factor authentication method (for convenience). So you don't actually have to press the button. Should this behavior be removed?
Or maybe the text on the button "Send authentication code" should be "Resend verification code" instead in that case.

**Comment by lucasvanhalst** [comment]
This is because the verification code gets send automatically as soon as you login, because you only have one two factor authentication method, so you don't actually have to press the button (for convenience). Should this behavior be removed, or should we simply update the text on the button from "Send authentication code" to "Resend authenticate code" in that case?
