### ISSUE TITLE
Can't send invitation to another user (using email address) to join existing organization  

### ISSUE THREAD

**Issue by john-kheir** [itsyouonline/identityserver#285]
## Scenario

1- Create account(1) with username : "kheirj"
2- Create account(2) with username: "andrew"
![0_user2](https://cloud.githubusercontent.com/assets/15011431/19728361/c2907392-9b9b-11e6-82ee-757e337b2334.png)

3- Create organization(gig_greenitglobe) for account1 and invite account(2) user using email address
![1_org_page](https://cloud.githubusercontent.com/assets/15011431/19728442/09ea35ca-9b9c-11e6-8cfd-8a230d3e414e.png)
## Actual Result

![2_sendinvite](https://cloud.githubusercontent.com/assets/15011431/19728463/1df2baec-9b9c-11e6-9fb8-a4048d6073e1.png)

**Comment by LeeSmet** [comment]
In the first screenshot, the account you try to invite doens't have a validated email address. Accounts can only be invited with validated email adresses.

**Comment by john-kheir** [comment]
Then, An appropriate message should be displayed other than "No user found matching this user name email address or phone number" .. because the user already exist on the system.
However i was able to invite a user with an unverified email, please check https://github.com/itsyouonline/identityserver/issues/287

**Comment by LeeSmet** [comment]
The thing is, this treats an email address as an alias to a username, so it should be verified (thereby also being unique). This is why it sais the user isn't found (because it literally can't find any user with that verified email address). If we would allow people to send invites to unconfirmed email addresses, we won't be able to determine what user should receive the invite, as multiple users could share the same unverified email address (creating security issues :) ).

**Comment by robvanmieghem** [comment]
This is deprecated by https://github.com/itsyouonline/identityserver/issues/299
