### ISSUE TITLE
Only lower cases are allowed when creating new organizations

### ISSUE THREAD

**Issue by yveskerwyn** [itsyouonline/identityserver#446]
![screen shot 2017-02-09 at 10 25 25](https://cloud.githubusercontent.com/assets/13795109/22777004/264ba258-eeb2-11e6-899f-bb16244267e8.png)

![screen shot 2017-02-09 at 10 25 31](https://cloud.githubusercontent.com/assets/13795109/22777014/2e6175f8-eeb2-11e6-857b-cefeb2f91750.png)

**Comment by LeeSmet** [comment]
This is by design, some small and capital letters look alike, which would possibly allow some organizations to trick unknowing users into sharing confidential information with them. At this point, this is an effective solution for this problem. It might be changed in the future. Or not.

tl;dr:
its not a bug, its a feature
