### ISSUE TITLE
Automatically verify email address

### ISSUE THREAD

**Issue by rvanoverbeke** [itsyouonline/identityserver#505]
We invite our users through Mobile phone numbers, and have integrated itsyou.online as much as possible in the MobieTrain app. This way users never need to log in on itsyou.online directly. 

This means that our users never see the need to manually verify their email address and have at this moment no means to recover their password if they forget it.

**Comment by LeeSmet** [comment]
as per https://github.com/itsyouonline/identityserver/issues/496, changes will be made to send a verification email as part of the registration flow. These verification links are valid for 48hours. This should give users plenty of time to verify their mail address,  allowing them to later do password recovery

**Comment by n-dury** [comment]
> These verification links are valid for 48hours

I would like to add the following to this.

As a user if I am not forced to verify an e-mail address prior to accessing a secured page using my login credentials I will most likely not verify the e-mail address. I've discussed this use case with several people ( both in IT and out ) and 

> "if I as a user am not forced to verify my e-mail address prior to being given access to my account I simply won't do it"

 is the general concensus.

Therefor I'd like to ask to remove the 48-hour criteria.
It would be much cleaner to "remind" the user he/she still has to verify his/her e-mail when logging in to IYO.

I understand keeping a DB table with all "unverified e-mails" can create a lot of data but not granting access to an account prior to validating your e-mail address might make people "bail out".

Kind regards,

Nickolas.

**Comment by LeeSmet** [comment]
Database space is not an issue. The issue here is that not expiring the link could potentially cause many users to leave an active email verification link on their system. Since this email address can then be used to reset a password and as a user identifier (login), this is a rather large security issue imo. Currently a notification is already shown when users have no verified email addresses. I feel like anything more then a notification can potentially be experienced as intrusive by a lot of people
