### ISSUE TITLE
users should not be able to create multiple accounts with the same email and mobile number

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#575]
account 1 
![image](https://user-images.githubusercontent.com/24386820/29280712-a4004292-811c-11e7-9874-78d4f28d9545.png)

account 2
![image](https://user-images.githubusercontent.com/24386820/29280746-c748df52-811c-11e7-814b-575f94747fc5.png)

### software version
staging envi
v0.9.14-53-g982fe24

**Comment by LeeSmet** [comment]
This is intentional. At least phone numbers are not unique for a given user: say that a user moves to another country. He cancels his mobile subscription with his telecom operator in his previous country. This operator will add the now invalid phone number back into the pool of available numbers after some time.  A new user can then receive this number. If we don't allow an existing number to be revalidated under a different accont, the person who receives this number could not create an IYO account. For emails we could consider "locking" them as they are supposed to be uniquely linked to a single person. Also note that any information can be registered by as many people as they want, though only be validated by a single person at once (for now)

**Comment by ahmedelsayed-93** [comment]
@LeeSmet 

but why it is possible to create two accounts with the same **verified** email and mobile ?

![image](https://user-images.githubusercontent.com/24386820/30519611-05f48ae2-9b9b-11e7-9bdc-851733f3ff9d.png)

![image](https://user-images.githubusercontent.com/24386820/30519615-31a26bf0-9b9b-11e7-85b9-ac815e008da3.png)

**Comment by LeeSmet** [comment]
Please confirm this by doing the following:
1. Create a new account with email E and phone number P
2. Make sure the email and account are verified (this is a part of the registration flow if you register on iyo, aka not in an oauth flow).
3. In a separate browser (or incognito window, just make sure the cookies are separated), create a new account using **THE SAME** email E and phone number P.
4. Make sure the email and phone number are verified on the second account
5. Go back to the previous browser. You will still be logged in. Now reload the page.
6. Check if the email and phone number are still marked as verified

**Comment by ahmedelsayed-93** [comment]
@LeeSmet 
ok your scenario is working and after reloading the page the mobile phone and the email became unverified 
but how to access the first account which doesn't have a verified email or phone number ?

**Comment by LeeSmet** [comment]
Access to the old account is restricted to the username (which is hidden from the user) in this scenario. But since an email address should belong to the same person, this is a very unlikely scenario. The only thing i can think about is if the user makes another account. But the idea of IYO is that an account represents your identity, so it does not make sense that a user has (access to ) multiple accounts.

Enforcing that an email address stays with the same user once it is verified could be done, but we should first do a thorough investigation if this will not cause issues in the future because of wrong assumptions about email address ownership

**Comment by ramezsaeed** [comment]
@LeeSmet Please reopen the issue until you do the investigation, so it can't be forgotten.
Thanks

**Comment by LeeSmet** [comment]
Since I feel that this is no longer closely related to the original issue, it is now tracked in #610
