### ISSUE TITLE
Can't find my username 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#576]
now the registration require the first name and the last name not the username
i can see only the first name and the last name in the portal but i can't find the my username

### software version
v0.9.14-53-g982fe24

**Comment by LeeSmet** [comment]
This is intentional, as we are going to drop username support in the long run. For now, we still use usernames under the hood because they function as keys in the db. However, all api calls where a user is targeted should be able to be performed with the validated userinfo instead (validated phone or email).
