### ISSUE TITLE
Move generated code in SMS to first line

### ISSUE THREAD

**Issue by dvorkbod** [itsyouonline/identityserver#592]
We can rephrase the SMS to put the code to be entered on the first line, so it is visible in typical phone previews.

**Comment by LeeSmet** [comment]
Since at least one translation key will require rearranging the variables in the function call instead of just changing the text, we should use this as an opportunity to introduce go's templating engne (package text/template). This will provide way more flexibility, allowing different parameter placement in different languages, or even omitting some parameters in a language.

**Comment by LeeSmet** [comment]
After some investigation, it seems that we can "embed" the templates into the json translations. So we first need to supply  a struct with the matching key(s) for the translation(s) we want to load, and then we provide a struct with the filled in values we want to apply. The benefit is that parameters are no longer positional but named. Also the templating engine does not care if a value is provided that it cannot use, so it is now technically possible to trim messages in certain languages

**Comment by LeeSmet** [comment]
templating enigne for translations introduced in df498db24782846826a7bda96a193c85787f76a7
