### ISSUE TITLE
can requests user:memberof:... scope from organization that doesn't exists

### ISSUE THREAD

**Issue by zaibon** [itsyouonline/identityserver#593]
when creating a JWT using client credential flow, I can create a jwt token that has some scope that I shouldn't have

Test script to generate token:
```python
def generatetoken(clientid, clientsecret, organization, scopes):
    params = {
        'grant_type': 'client_credentials',
        'client_id': clientid,
        'client_secret': clientsecret,
        'response_type': 'id_token',
        'scope': scopes,
    }


    url = 'https://itsyou.online/v1/oauth/access_token'
    resp = requests.post(url, params=params)
    resp.raise_for_status()
    token = resp.content.decode('utf8')
    print("export JWT='{}'".format(token))
```

Wen asking a scope like `user:memberof:nonexistingorg` the token created contains an empty scopes filed. Which is ok.
But if I ask a scope like `user:memberof:myorg.nonexistingorg`, the token created contains the asked scope, even if `myorg.nonexistingorg` is not a sub organization that exists.

**Comment by LeeSmet** [comment]
The issue here is the following:

Database checks if the user is member of `myorg.nonexistingsuborg`, which is obviously not the case since this org does not exist. So the logic then checks ifs the user is a member of `myorg`, as this is a parent org of `nonexistingsuborg`, and by membership inheritance rules, being a member of `myorg` then makes you a member of `nonexistingsuborg` as well. A simple check to see if `myorg.nonexistingsuborg` exists first should fix this AFAIC

**Comment by zaibon** [comment]
I've been told that you can be member of a sub-organisation without being member of the root organization. Is this assumption correct ? Cause if not we are changing a rule that could impact other use cases no ?

**Comment by LeeSmet** [comment]
Not sure i fully understand your question, however:

It is possible to be a member of a suborg without being in the rootorg: say i have an organization `A` with suborganization `B` (so full name is `A.B`), then i can be a member of `B` without being a member in `A`. If i were to be a member of `A`, then I am also a member of `A.B`, since membership is inherited to suborganizations.

The fix does not change any functionality, it simply prevents the memberof scope from being given for a suborganization that does not exist if you are a member of the parent organization. If you have the structure `myorg.nonexistingsuborg`, you got the memberof scope because the system recognized you as a member of `myorg`, and this implied membership of `nonexistingsuborg`. The db logic has simply been made aware that it should check if a suborg exists first before confirming (implicit) membershp (because you obviously can't be a member of an nonexisting organization).

**Comment by zaibon** [comment]
Ok so my assumptions were correct. all good :+1:

**Comment by LeeSmet** [comment]
Moved to bugfix release branch
