### ISSUE TITLE
Login button requires repeated email validation if the resend functionality is used

### ISSUE THREAD

**Issue by bart-at-mobicage** [itsyouonline/identityserver#597]
I create new account using my iPhone browser and accidentally filled in a wrong phone number. After verifying my email, I went back to the INFO step, corrected my phone number. Went back to the VALIDATION step. Click "RESEND..." and validated my phone number. And then clicking the LOGIN button did nothing.

**Comment by LeeSmet** [comment]
Was this a "normal" registration or part of an oauth flow. If so, what scopes were requested?

**Comment by LeeSmet** [comment]
It seems that the server resends an email validation request even if the email address is already validated. The login handler then checks if the new validation request has been completed before allowing login

**Comment by LeeSmet** [comment]
This is acutally caused by multiple issues:
- When info on the first registration page changes, a new user is created in the db, instead of an update of the previous user.
- When the resend validation is triggered, the old key is simply invalidated an a new validation with a new key stored.

When the registration is completed, the validationkey for the last request is checked to see if it is confirmed.

**Comment by LeeSmet** [comment]
Moved to bugfix release branch
