### ISSUE TITLE
Scopes get removed if you execute the authorise flow with other scopes

### ISSUE THREAD

**Issue by lucasvanhalst** [itsyouonline/identityserver#599]
Usecase: 

- User logs in on website 1, scopes: email, name and phone number
- User logs in on website 2, scopes: email.

If the user logs in on website 1 and then on website 2 only the email scope will be given to the organisation, the name and phone number scope will be removed.

**Comment by LeeSmet** [comment]
It would indeed make sense to just extend an already existing authorization I think, but this will require some backend changes so I feel we should also consider this in the context of #600

**Comment by LeeSmet** [comment]
Moved to bugfix release milestone

**Comment by LeeSmet** [comment]
2 Things need to happen:

1. When the existing authorization is checked, verify that all the requested scopes are already provided rather than checking the length of the scope array for an exact match.
2. If a new authorization is given, append it to an existing one ( overwriting the scopes that have an exact name match )
