### ISSUE TITLE
Get user's organizations returns 403

### ISSUE THREAD

**Issue by islamTaha12** [itsyouonline/identityserver#614]
**Steps:**
- Create a user client
- Get the user information by the client
- Try to get the user organizations 

```python
ipdb> self.iyo_master_client.api.GetUserInformation('tahai@greenitglobe.com')
<Response [200]>

ipdb> self.iyo_master_client.api.GetUserOrganizations('tahai@greenitglobe.com')
<Response [403]>
```

**Comment by LeeSmet** [comment]
I'd like to know how this access token or jwt was created, specifically, what scopes were requested / stored

**Comment by islamTaha12** [comment]
@LeeSmet Here is how i get a client
```python
self.iyo_slave_client = Client(config['main']['iyo_url'])
self.iyo_slave_client.oauth.login_via_client_credentials(client_id=iyo_user2_id, client_secret=iyo_user2_secret)
```

And here is the client class:
https://github.com/ahmedelsayed-93/identityserver/blob/travis_tests/tests/api_testing/testframework/client.py

**Comment by robvanmieghem** [comment]
@islamTaha12 even though the first call gives you a 200 response code, what is the body of the response? I suspect it is pretty empty since you are authorized as ' iyo_user2_id while requesting the info of 'tahai@greenitglobe.com so no appropriate scopesare presents o off course you can not request the orgs he is member of and you get a 403

**Comment by LeeSmet** [comment]
@robvanmieghem the issue is that the used endpoint was not wrapped by the user identifier middleware which replaces the validated email address/phone number with the username before passing through the authorization. As a result of this, the authentication middleware did not recognize the access token. I forgot to add this middleware to the 3 endpoints in the userorganization endpoint back in the day when this was done for all the rest. So this is actually an issue on our end

**Comment by LeeSmet** [comment]
Putting this back to state verification since it was acutally a bug and has been solved, but isn't on master / production yet

**Comment by ahmedelsayed-93** [comment]
### Version
staging server 
v0.9.16-115-g0eefc1a
