### ISSUE TITLE
Can we store user:address

### ISSUE THREAD

**Issue by samaradel** [itsyouonline/identityserver#625]
![screenshot-2017-9-25 itsyouonline identityserver](https://user-images.githubusercontent.com/11662805/30804490-4fd4cd64-a1f6-11e7-9bae-923b926c09c8.png)

**Comment by LeeSmet** [comment]
As per the docs, this is currently not possible. Since an address object is rather large, we should consider how or even if we want to support this. Since addresses aren't used to identify users or restrict access like the emails and phone numbers are, this also isn't urgent. This might be done in the (not so near) future. 

P.S.: Getting the address if a jwt is provided only requires a single call anyway

**Comment by samaradel** [comment]
I know it's large but i think we could split it to fill intercom fields [#118](https://docs.greenitglobe.com/ThreeFold/www_threefold2.0/issues/118) 

![screenshot-2017-9-27 user model](https://user-images.githubusercontent.com/11662805/30902461-0e62ba2e-a374-11e7-8e6d-3e943d93c9e0.png)

besides we need **user:see,user:keystore,user:address,user:memberOf:threefold** for [#146](https://docs.greenitglobe.com/ThreeFold/www_threefold2.0/issues/146)

**Comment by robvanmieghem** [comment]
@samaradel unless there is a really important use case, I agree wit @LeeSmet, closing this for now
