### ISSUE TITLE
Listing user organizations is very slow

### ISSUE THREAD

**Issue by lucasvanhalst** [itsyouonline/identityserver#636]
For me it takes 7 seconds to load the list of organisations that I am in.

Issue is that this method goes to the database multiple times for every organisation the user is in. It should be limited to at most 3 or 4 calls to the database.
Instead of looping over the organisations and doing a call to the database for each of them, first do a call to the database to fetch all organisations and then loop over them. 
https://github.com/itsyouonline/identityserver/blob/cb804a7c7c8b8463294b4c62bbe7eeac5da03c5a/db/organization/db.go#L402-L572

**Comment by LeeSmet** [comment]
Reducing the amount of database calls will probably be impossible since we need to progressively discover organizations. This would be a breeze for graph databases, which mongo sadly is not. Though it seems that their is also a lot of time spend rendering also takes a lot of time

**Comment by lucasvanhalst** [comment]
A "simple" fix would be to only show top-level organizations in the organization list I guess, and when you click the plus only then it fetches sub organizations

**Comment by LeeSmet** [comment]
Unfortunately, due to organization membership rules, it is possible that e.g. membership of a suborganization, which is inherited from the parent, gives membership in a different top level organization. This means that we need to load in all organizations to be 100% sure that we indeed found all top level orgs. Some more extensive profiling will need to be done to determine if the slow results are caused by a particular part in the code or just a combination of everything. In either case, the javascript also takes a long time to render the tree (multiple seconds). So some profiling there will also be done. There are 2 phases: sorting and parsing the orgs into the tree. Should sorting be a time issue, we could move that to the backend. The current api makes no guarantees about how the data comes out so this won't cause any issue and it is likely faster (though this should only be done if it is a significant performance improvement). If the parsing is the major problem, we could change the sort to return top level orgs first, and see if the tree can render results as it parses them.

**Comment by LeeSmet** [comment]
Some refactoring has been done to significantly reduce the amount of db calls performed. This probably can be optimized further, but doing so will exponentially increase code complexity. Before proceeding with this, lets first check how the new code performs

**Comment by ahmedelsayed-93** [comment]
it took 101 ms to list user organizations ( 3 organization x 4 sub organization)
![image](https://user-images.githubusercontent.com/24386820/35608882-c3d4931c-0663-11e8-916b-4431099a1076.png)

### Version
staging server 
v0.9.16-115-g0eefc1a
