### ISSUE TITLE
Arrived back at step 1 after registration (Safari on iOS 8)

### ISSUE THREAD

**Issue by bart-at-mobicage** [itsyouonline/identityserver#645]
I went through steps 1, 2 and 3. Clicked login and ended back at step 1.

Happened on iPhone 5S simulator with iOS 8.1

<img width="432" alt="screen shot 2017-10-07 at 17 38 09" src="https://user-images.githubusercontent.com/17762105/31309442-85fd9742-ab86-11e7-9ce0-d7ecc42a2b3d.png">

**Comment by LeeSmet** [comment]
how much time passed since you filled in all your info in step 1 and pressed login in step 3?

**Comment by LeeSmet** [comment]
## After investigation:

- Happens on iOs 8.1 (iPhone 5S, simulator)
- Happens on both `staging` and `lee.itsyou.online`, but not when connecting via the IP address the url points to

**Comment by LeeSmet** [comment]
it seems that for some reason, the `username` value is not set in the `authenticatedsession` cookie after the registration flow on iOS 8.1

**Comment by LeeSmet** [comment]
Also happens on iOS 8.2, but not on 8.3 or 8.4. 9 and higher also work fine.

After checking the response headers, the 'set cookie' headers are indeed available as expected. since this is managed by the backend, which doesn't distinguish between different browsers etc, it's becoming increasingly weird that this only happens in these safari versions and not in all browsers.

To further complicate things, this only happens when connecting through a `xxx.itsyou.online` url, not when using the ip address to connect.

**Comment by bart-at-mobicage** [comment]
might be useful to show a "Your browser is not supported" message
