### ISSUE TITLE
Leave organization doesn't work correctly 

### ISSUE THREAD

**Issue by Dinaamagdy** [itsyouonline/identityserver#673]
## Steps 
- We create itsonline user, and make it join one of openvcloud organiztions .
- Check from openvcloud that user actually join this organization.
- then make this user leave this organization from setting 
- Check from openvcloud that user actually leave  this organization.

## Issue 
user still exist in this orgnization , although if the admin of this organization kicks this user out of organization it will work correctly.

**Comment by LeeSmet** [comment]
It seems that I am currently unable to reproduce this behaviour. I checked and as far as I can tell leaving an organization works (Note that due to owner/membership inheritance it might seem like the user is still a part of the organization, while he is really part of a parent organization or an included organization).

Also, since you are mentioning third party integrations, please verify that there is no caching there, as a cached state might prevent an immediate reflection of an ItsYou.online change.

Please provide more details such as the organization setup, a clear overview of what happens where (e.g. I go into the organization settings on iyo and leave the organization, then I immediately go to openvcloud to verify that I have left the organization,...)

**Comment by LeeSmet** [comment]
@Dinaamagdy ?

**Comment by LeeSmet** [comment]
Closing due to lack of response
