### ISSUE TITLE
make it possible to control the expiration time

### ISSUE THREAD

**Issue by GlenDC** [itsyouonline/identityserver#684]
Currently the expiration time seems to be hardcoded at 24 hours, as can be seen at: https://github.com/itsyouonline/identityserver/blob/3121c59e1ad255fb4142855d91c70e26d37d2761/oauthservice/access_token.go#L18-L19

This is however a very long time. While this is perhaps OK as a default (but really, is it?), I would love to be able to customize this (expiration time) when I request a JWT token.

As I'm developing 0-stor, I would love to request JWT tokens there, which expire after 10 minutes.

**Comment by LeeSmet** [comment]
While the expiration date is indeed hardcoded for for access tokens, I feel like it generally wouldn't have any added value to allow this to be customized. Access tokens are meant to be kept on server and not transmitted. Since the server is the only user of the access token, it can decide for itself how long it wants to keep using it.

In contrast, JWT's can be used in communication between the original requesting server and another entity, and they do support a limited validity period: See https://github.com/itsyouonline/identityserver/blob/master/docs/oauth2/jwt.md#jwt-expiration-date. JWT's also have support for the optional refresh token, whereas access tokens do not have such an option (effectively requiring the user to login again in order to get a new access token).

As in your request, it should suffice to add the `validity=600` parameter when requesting the JWT.

**Comment by GlenDC** [comment]
Yes, I use a validity of "`300`", now, and I can confirm that this indeed gives me a lifetime for 5 minutes, so this is exactly what I wanted to achieve. Didn't know it was possible, tried looking for answers in the documentation, and couldn't find it on my own.

Thank you.
