### ISSUE TITLE
Internal server error when trying to register a new account

### ISSUE THREAD

**Issue by ahmedelsayed-93** [itsyouonline/identityserver#697]
once i filled the required fields and click on next button 
i got this error, and in the same time i have received the verification SMS  

![image](https://user-images.githubusercontent.com/24386820/35559753-268028e2-05b4-11e8-9341-339ffd3d3779.png)

### Version
staging server
```{"Version":"v0.9.16-114-gdb03c0e"}```

**Comment by LeeSmet** [comment]
Issue was a duplicate key error for the email validation key (empty key) because it is not sent instantly. This uniqueness is not required on this object, since its already enforced in the respective ongoing email address validation collection ( same for phone number)

Fixed in 0eefc1ae821c6bafdaec3f7a25f3f56c87756e92

**Comment by ahmedelsayed-93** [comment]
### Version
staging server 
v0.9.16-115-g0eefc1a
